Chunks and mipmaps
idia-astro/cpp_hdf5converter pull request #20
Opened 2019-11-22 11:08 UTC by confluence

This PR adds chunked datasets and mipmaps and a slow conversion which converts a channel at a time. It also extends the tests and fixes a range of small issues uncovered during testing. I have bumped the schema version.

2019-11-23 19:25 UTC, veggiesaurus requested changes
`main.cc` is getting a little unwieldy. Can you move the image class to its own header and implementation?

2019-11-23 20:16 UTC, confluence commented
That's a good idea. I'll maybe move the supplementary classes out to a different file as well.

2019-11-25 13:06 UTC, confluence commented
I split up the code into multiple files. How does this look? The other helper classes are so small that it seemed unnecessary to split them into header and implementation.

I created a header file for common imports so that we could avoid importing the same headers into multiple helper classes (although I think they all have `#ifndef` guards anyway), and so that we wouldn't have to micromanage exactly which files use which std library headers. And also to put the global constants in one sensible place.

I would also still like to split the fast and slow implementations into subclasses.

2020-02-04 08:28 UTC, veggiesaurus approved these changes

2020-02-04 08:51 UTC, merged